# CFReT Buscar analysis

This notebook demonstrates applying the BUSCAR pipeline to the CFReT pilot Cell Painting dataset.
It walks through data loading, signature extraction, clustering, measuring phenotypic activity
(between a reference control and experimental treatments) and ranking treatments by effect.

Data & references
- Data source: CFReT pilot dataset (see paper: https://www.ahajournals.org/doi/full/10.1161/CIRCULATIONAHA.124.071956)
- Original data repo: https://github.com/WayScience/cellpainting_predicts_cardiac_fibrosis

In [1]:
import sys
import json
import pathlib

import polars as pl

sys.path.append("../../")
from utils.io_utils import load_profiles

# from utils.metrics import measure_phenotypic_activity
from utils.data_utils import split_meta_and_features
from buscar.signatures import get_signatures
from buscar.metrics import measure_phenotypic_activity

Setting paramters

In [2]:
# setting parameters
treatment_col = "Metadata_cell_type_and_treatment"

# buscar parameters
healthy_label = "healthy_DMSO"
failing_label = "failing_DMSO"
on_off_signatures_method = "ks_test"

Setting input and output paths

In [3]:
# load in raw data from
cfret_data_dir = pathlib.Path("../0.download-data/data/sc-profiles/cfret/").resolve(
    strict=True
)
cfret_profiles_path = (
    cfret_data_dir / "localhost230405150001_sc_feature_selected.parquet"
).resolve(strict=True)
cfret_feature_space_path = (
    cfret_data_dir / "cfret_feature_space_configs.json"
).resolve(strict=True)

# make results dir
results_dir = pathlib.Path("./results").resolve()
results_dir.mkdir(parents=True, exist_ok=True)

# set signatures results dir
signatures_results_dir = (results_dir / "signatures").resolve()
signatures_results_dir.mkdir(parents=True, exist_ok=True)

# set phenotypic scores results dir
phenotypic_scores_results_dir = (results_dir / "phenotypic_scores").resolve()
phenotypic_scores_results_dir.mkdir(parents=True, exist_ok=True)

Data preprocessing 
-

In [4]:
# loading profiles
cfret_df = load_profiles(cfret_profiles_path)

# add another metadata column that combins both Metadata_heart_number and Metadata_treatment
cfret_df = cfret_df.with_columns(
    (
        pl.col("Metadata_treatment").cast(pl.Utf8)
        + "_heart_"
        + pl.col("Metadata_heart_number").cast(pl.Utf8)
    ).alias("Metadata_treatment_and_heart")
)

# renaming Metadata_treatment to Metadata_cell_type + Metadata_treatment
cfret_df = cfret_df.with_columns(
    (
        pl.col("Metadata_cell_type").cast(pl.Utf8)
        + "_"
        + pl.col("Metadata_treatment").cast(pl.Utf8)
    ).alias(treatment_col)
)

# split features
cfret_meta, cfret_feats = split_meta_and_features(cfret_df)


# Display data
cfret_df.head()

shape: (5, 679)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Metadata_ ┆ Metadata_ ┆ Metadata_ ┆ Metadata_ ┆ … ┆ Nuclei_Te ┆ Nuclei_Te ┆ Metadata_ ┆ Metadata │
│ cell_id   ┆ WellRow   ┆ WellCol   ┆ heart_num ┆   ┆ xture_Sum ┆ xture_Sum ┆ treatment ┆ _cell_ty │
│ ---       ┆ ---       ┆ ---       ┆ ber       ┆   ┆ Variance_ ┆ Variance_ ┆ _and_hear ┆ pe_and_t │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ Mit…      ┆ PM_…      ┆ t         ┆ reatme…  │
│           ┆           ┆           ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 210e4376e ┆ B         ┆ 2         ┆ 9         ┆ … ┆ -0.263653 ┆ -0.305486 ┆ DMSO_hear ┆ failing_ │
│ fde9d557a ┆           ┆           ┆           ┆   ┆           ┆           ┆ t_9       ┆ DMSO     │
│ 5c60029bd ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ da6…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cef18f209 ┆ B         ┆ 2         ┆ 9         ┆ … ┆ 2.621455  ┆ -0.175679 ┆ DMSO_hear ┆ failing_ │
│ 640ef8ae9 ┆           ┆           ┆           ┆   ┆           ┆           ┆ t_9       ┆ DMSO     │
│ 8ec110cfd ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cb6…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cca07fa58 ┆ B         ┆ 2         ┆ 9         ┆ … ┆ -0.23489  ┆ -0.312005 ┆ DMSO_hear ┆ failing_ │
│ 1da808fde ┆           ┆           ┆           ┆   ┆           ┆           ┆ t_9       ┆ DMSO     │
│ fe80f9c05 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 42d…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c076728ed ┆ B         ┆ 2         ┆ 9         ┆ … ┆ -0.148249 ┆ -0.205381 ┆ DMSO_hear ┆ failing_ │
│ 2ebba7c01 ┆           ┆           ┆           ┆   ┆           ┆           ┆ t_9       ┆ DMSO     │
│ e6adb4244 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b02…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2e8f5f11d ┆ B         ┆ 2         ┆ 9         ┆ … ┆ 0.054053  ┆ -0.346036 ┆ DMSO_hear ┆ failing_ │
│ 29d8f82ba ┆           ┆           ┆           ┆   ┆           ┆           ┆ t_9       ┆ DMSO     │
│ a39f573e2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e51…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Display the treatments and number of cells per heart-treatment combination

In [5]:
# show how many cells per treatment
# shows the number of cells per treatment that will be clustered.
cells_per_treatment_counts = cfret_df.group_by(treatment_col).len().sort(treatment_col)
cells_per_treatment_counts

shape: (4, 2)
┌─────────────────────────────────┬──────┐
│ Metadata_cell_type_and_treatme… ┆ len  │
│ ---                             ┆ ---  │
│ str                             ┆ u32  │
╞═════════════════════════════════╪══════╡
│ failing_DMSO                    ┆ 9153 │
│ failing_TGFRi                   ┆ 3788 │
│ healthy_DMSO                    ┆ 1366 │
│ healthy_TGFRi                   ┆ 1486 │
└─────────────────────────────────┴──────┘

## BUSCAR pipeline

### Creating on and off morphology signatures

Here we generate the **on** and **off** morphological signatures to distinguish how phenotypes respond to treatments.

On-Target Signatures (`on_sigs`):

These represent the features that show a **significant statistical shift** from both the control group and the phenotype of interest. We use these to identify the specific morphological changes driven by the experimental conditions.

Off-Target Features (`off_sigs`):

These are the features that remain **unaffected** when comparing the control against the phenotype. This provides a critical baseline, helping us understand which biological markers should stay stable even when a compound is applied.

In [6]:
# setting output paths
signatures_outpath = (signatures_results_dir / "cfret_pilot_signatures.json").resolve()

if signatures_outpath.exists():
    print("Signatures already exist, skipping this step.")
    with open(signatures_outpath, "r") as f:
        sigs = json.load(f)
        on_sigs = sigs["on"]
        off_sigs = sigs["off"]
else:
    # once the data is loaded, separate the controls
    negcon_df = cfret_df.filter(pl.col(treatment_col) == failing_label)
    poscon_df = cfret_df.filter(pl.col(treatment_col) == healthy_label)

    # creating signatures
    on_sigs, off_sigs, _ = get_signatures(
        ref_profiles=negcon_df,
        exp_profiles=poscon_df,
        morph_feats=cfret_feats,
        test_method=on_off_signatures_method,
    )

    # Save signatures as json file
    with open(signatures_outpath, "w") as f:
        json.dump({"on": on_sigs, "off": off_sigs}, f, indent=4)

Signatures already exist, skipping this step.

### Measuring phenotypic activity

This section quantifies how each treatment affects cell morphology compared to the reference control (DMSO_heart_11), using the previously defined on and off signatures. The resulting phenotypic scores are used to rank treatments and highlight the most active compounds.

**How scores are calculated:**

- **On-signature features:** We use the Earth Mover's Distance (EMD) to measure how much the on-features for each treatment differ from the reference. A higher EMD means a greater morphological change.
- **Off-signature features:** We use the affected ratio, which detects if features that should remain stable (off-features) are altered by a treatment. A higher affected ratio suggests more off-target or unintended effects.

In summary, low on-signature scores indicate strong, intended phenotypic changes, while high off-signature scores may indicate unwanted or broad effects.

In [7]:
treatment_scores = measure_phenotypic_activity(
    profiles=cfret_df,
    meta_cols=cfret_meta,
    on_signature=on_sigs,
    off_signature=off_sigs,
    ref_state=healthy_label,
    target_state=failing_label,
    on_method="emd",
    off_method="affected_ratio",
    ratio_stats_method=on_off_signatures_method,
    treatment_col=treatment_col,
)

# save phenotypic scores
treatment_scores.write_csv(
    phenotypic_scores_results_dir / "cfret_pilot_phenotypic_scores.csv"
)

/home/erikserrano/Software/miniconda3/envs/buscar/lib/python3.12/site-packages/ot/lp/__init__.py:630: UserWarning: numItermax reached before optimality. Try to increase numItermax.
  check_result(result_code)
/home/erikserrano/Projects/buscar/buscar/metrics.py:425: DataOrientationWarning: Row orientation inferred during DataFrame construction. Explicitly specify the orientation by passing `orient="row"` to silence this warning.
  scores_df = pl.DataFrame(

In [8]:
treatment_scores

shape: (3, 5)
┌──────┬──────────────┬───────────────┬──────────┬───────────┐
│ rank ┆ ref_profile  ┆ treatment     ┆ on_score ┆ off_score │
│ ---  ┆ ---          ┆ ---           ┆ ---      ┆ ---       │
│ u32  ┆ str          ┆ str           ┆ f64      ┆ f64       │
╞══════╪══════════════╪═══════════════╪══════════╪═══════════╡
│ 1    ┆ healthy_DMSO ┆ healthy_TGFRi ┆ 0.681427 ┆ 0.147059  │
│ 2    ┆ healthy_DMSO ┆ failing_TGFRi ┆ 0.904196 ┆ 0.264706  │
│ 3    ┆ healthy_DMSO ┆ failing_DMSO  ┆ 1.0      ┆ 0.0       │
└──────┴──────────────┴───────────────┴──────────┴───────────┘