In [1]:
import sys
import pathlib

import polars as pl

sys.path.append("../../")
from utils.io_utils import load_profiles, load_configs
from scipy.stats import ks_2samp
from statsmodels.stats.multitest import fdrcorrection
from utils.data_utils import split_meta_and_features

In [2]:
# load in raw data from
cfret_data_dir = pathlib.Path("../0.download-data/data/sc-profiles/cfret/").resolve(
    strict=True
)
cfret_profiles_path = (
    cfret_data_dir / "localhost230405150001_sc_feature_selected.parquet"
).resolve(strict=True)
cfret_feature_space_path = (
    cfret_data_dir / "cfret_feature_space_configs.json"
).resolve(strict=True)

# make results dir
results_dir = pathlib.Path("./results").resolve()
results_dir.mkdir(parents=True, exist_ok=True)

# signatures effect
signatures_results_dir = pathlib.Path(results_dir / "signatures")
signatures_results_dir.mkdir(exist_ok=True)

In [3]:
# setting parameters
treatment_col = "Metadata_cell_type_and_treatment"

# buscar parameters
healthy_label = "healthy_DMSO"
failing_label = "failing_DMSO"
on_off_signatures_method = "ks_test"

In [4]:
# loading profiles
cfret_df = load_profiles(cfret_profiles_path)

# load cfret_df feature space and update cfret_df
cfret_feature_space = load_configs(cfret_feature_space_path)
cfret_meta_features = cfret_feature_space["metadata-features"]
cfret_features = cfret_feature_space["morphology-features"]
cfret_df = cfret_df.select(pl.col(cfret_meta_features + cfret_features))

# add another metadata column that combins both Metadata_heart_number and Metadata_treatment
cfret_df = cfret_df.with_columns(
    (
        pl.col("Metadata_treatment").cast(pl.Utf8)
        + "_heart_"
        + pl.col("Metadata_heart_number").cast(pl.Utf8)
    ).alias("Metadata_treatment_and_heart")
)

# renaming Metadata_treatment to Metadata_cell_type + Metadata_treatment
cfret_df = cfret_df.with_columns(
    (
        pl.col("Metadata_cell_type").cast(pl.Utf8)
        + "_"
        + pl.col("Metadata_treatment").cast(pl.Utf8)
    ).alias(treatment_col)
)

# split features
cfret_meta, cfret_feats = split_meta_and_features(cfret_df)

# Display data
print(f"Dataframe shape: {cfret_df.shape}")
cfret_df.head()

Dataframe shape: (15793, 679)

shape: (5, 679)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Metadata_ ┆ Metadata_ ┆ Metadata_ ┆ Metadata_ ┆ … ┆ Nuclei_Te ┆ Nuclei_Te ┆ Metadata_ ┆ Metadata │
│ cell_id   ┆ WellRow   ┆ WellCol   ┆ heart_num ┆   ┆ xture_Sum ┆ xture_Sum ┆ treatment ┆ _cell_ty │
│ ---       ┆ ---       ┆ ---       ┆ ber       ┆   ┆ Variance_ ┆ Variance_ ┆ _and_hear ┆ pe_and_t │
│ str       ┆ str       ┆ i64       ┆ ---       ┆   ┆ Mit…      ┆ PM_…      ┆ t         ┆ reatme…  │
│           ┆           ┆           ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 210e4376e ┆ B         ┆ 2         ┆ 9         ┆ … ┆ -0.263653 ┆ -0.305486 ┆ DMSO_hear ┆ failing_ │
│ fde9d557a ┆           ┆           ┆           ┆   ┆           ┆           ┆ t_9       ┆ DMSO     │
│ 5c60029bd ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ da6…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cef18f209 ┆ B         ┆ 2         ┆ 9         ┆ … ┆ 2.621455  ┆ -0.175679 ┆ DMSO_hear ┆ failing_ │
│ 640ef8ae9 ┆           ┆           ┆           ┆   ┆           ┆           ┆ t_9       ┆ DMSO     │
│ 8ec110cfd ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cb6…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cca07fa58 ┆ B         ┆ 2         ┆ 9         ┆ … ┆ -0.23489  ┆ -0.312005 ┆ DMSO_hear ┆ failing_ │
│ 1da808fde ┆           ┆           ┆           ┆   ┆           ┆           ┆ t_9       ┆ DMSO     │
│ fe80f9c05 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 42d…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c076728ed ┆ B         ┆ 2         ┆ 9         ┆ … ┆ -0.148249 ┆ -0.205381 ┆ DMSO_hear ┆ failing_ │
│ 2ebba7c01 ┆           ┆           ┆           ┆   ┆           ┆           ┆ t_9       ┆ DMSO     │
│ e6adb4244 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b02…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2e8f5f11d ┆ B         ┆ 2         ┆ 9         ┆ … ┆ 0.054053  ┆ -0.346036 ┆ DMSO_hear ┆ failing_ │
│ 29d8f82ba ┆           ┆           ┆           ┆   ┆           ┆           ┆ t_9       ┆ DMSO     │
│ a39f573e2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e51…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
ref_df = cfret_df.filter(pl.col("Metadata_cell_type_and_treatment") == failing_label)
target_df = cfret_df.filter(pl.col("Metadata_cell_type_and_treatment") == healthy_label)

In [6]:
# apply ks test to each feature (single loop)
ks_stats = []
p_values = []
for feature in cfret_feats:
    stat, p_value = ks_2samp(ref_df[feature], target_df[feature])
    ks_stats.append(stat)
    p_values.append(p_value)

# FDR correction (vectorized)
_, p_values_fdr = fdrcorrection(p_values)

# Create DataFrame
ks_results_df = pl.DataFrame(
    {
        "feature": cfret_feats,
        "p_value": p_values,
        "ks_stat": ks_stats,
        "p_value_fdr_corrected": p_values_fdr,
    }
)

# Vectorized log transformation
ks_results_df = ks_results_df.with_columns(
    (-pl.col("p_value_fdr_corrected").log10()).alias("neg_log10_p_value")
)

# add a column for significance based on a threshold (e.g., 0.05)
# if lower than 0.05 then there should be a label known as "on" and higher than 0.05 should be "off"
ks_results_df = ks_results_df.with_columns(
    pl.when(pl.col("p_value_fdr_corrected") < 0.05)
    .then(pl.lit("on"))
    .otherwise(pl.lit("off"))
    .alias("signature")
)

# add a column of "channel" where we splitthe feature name and takethe first split
ks_results_df = ks_results_df.with_columns(
    pl.col("feature").str.split("_").list.get(0).alias("channel")
)

# save dataframe as csv
ks_results_df.write_csv(signatures_results_dir / "signature_importance.csv")

# display
print(ks_results_df.shape)
ks_results_df.head()

(657, 7)

shape: (5, 7)
┌────────────────┬────────────┬──────────┬────────────────┬────────────────┬───────────┬───────────┐
│ feature        ┆ p_value    ┆ ks_stat  ┆ p_value_fdr_co ┆ neg_log10_p_va ┆ signature ┆ channel   │
│ ---            ┆ ---        ┆ ---      ┆ rrected        ┆ lue            ┆ ---       ┆ ---       │
│ str            ┆ f64        ┆ f64      ┆ ---            ┆ ---            ┆ str       ┆ str       │
│                ┆            ┆          ┆ f64            ┆ f64            ┆           ┆           │
╞════════════════╪════════════╪══════════╪════════════════╪════════════════╪═══════════╪═══════════╡
│ Cytoplasm_Area ┆ 0.000128   ┆ 0.063555 ┆ 0.00015        ┆ 3.825207       ┆ on        ┆ Cytoplasm │
│ Shape_Bounding ┆            ┆          ┆                ┆                ┆           ┆           │
│ Bo…            ┆            ┆          ┆                ┆                ┆           ┆           │
│ Cytoplasm_Area ┆ 0.784666   ┆ 0.018836 ┆ 0.789473       ┆ 0.102663       ┆ off       ┆ Cytoplasm │
│ Shape_Compactn ┆            ┆          ┆                ┆                ┆           ┆           │
│ es…            ┆            ┆          ┆                ┆                ┆           ┆           │
│ Cytoplasm_Area ┆ 3.8892e-47 ┆ 0.211618 ┆ 9.9039e-47     ┆ 46.004195      ┆ on        ┆ Cytoplasm │
│ Shape_Eccentri ┆            ┆          ┆                ┆                ┆           ┆           │
│ ci…            ┆            ┆          ┆                ┆                ┆           ┆           │
│ Cytoplasm_Area ┆ 1.8732e-21 ┆ 0.142288 ┆ 3.1395e-21     ┆ 20.503135      ┆ on        ┆ Cytoplasm │
│ Shape_Extent   ┆            ┆          ┆                ┆                ┆           ┆           │
│ Cytoplasm_Area ┆ 0.784666   ┆ 0.018836 ┆ 0.789473       ┆ 0.102663       ┆ off       ┆ Cytoplasm │
│ Shape_FormFact ┆            ┆          ┆                ┆                ┆           ┆           │
│ or             ┆            ┆          ┆                ┆                ┆           ┆           │
└────────────────┴────────────┴──────────┴────────────────┴────────────────┴───────────┴───────────┘